apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibi-web-server-deployment
  labels:
        dep: bibi-web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: my-web-app
        image: bibiefrat/ci-cd-1:my-web-app
        env:
        - name: MONGO_URL_RUN
          value: "mongodb://10.100.1.143:20000"
        - name: MONGO
          value: "127.0.0.1"
        ports:
        - containerPort: 8088
      - name: mongo
        image: bibiefrat/ci-cd-1:my-mongo
        env:
        - name: MONGO_URL_RUN
          value: "mongodb://10.100.1.143:20000"
        ports:
        - containerPort: 27017
 
---
    
apiVersion: v1
kind: Service
metadata:
  name: bibi-web-server-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - name: "http"
      port: 8088
      targetPort: 8088
      nodePort: 30080
