FROM jenkins/inbound-agent

USER root

RUN apt-get update \
    && apt-get install -y curl \
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod 777 kubectl \
    && mv kubectl /bin

USER jenkins

