pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  agent {
      kubernetes {
          label 'bibi-web-app'
          idleMinutes 5
          yamlFile 'microservices-in-two-pods-fleet-dynamic-jenkins-on-ebs/jenkins_eks.yaml'
          defaultContainer 'jnlp'
       }
   }
 stages {
    stage('Push') {
      steps {
            container('inbound-agent') {
              sh """
                 kubectl get svc
                 cd microservices-in-two-pods-fleet-dynamic-jenkins-on-ebs
                 kubectl apply -f bibi-ns.yaml
                 kubectl apply -f mongo-secret.yaml -n bibi-devops-tools
                 kubectl apply -f mongo-svc.yaml -n bibi-devops-tools
                 kubectl apply -f mongodb-deployment.yaml -n bibi-devops-tools
                 kubectl apply -f bibi_web_server_ex1.yaml -n bibi-devops-tools
                 sleep 60
              """
        }
      }//steps
    }//stage
  }//stages
post {
        always {
            container('inbound-agent') {
                  sh """
                    cd microservices-in-two-pods-fleet-dynamic-jenkins-on-ebs
                    kubectl delete -f bibi_web_server_ex1.yaml -n bibi-devops-tools
                    kubectl delete -f mongodb-deployment.yaml -n bibi-devops-tools
                    kubectl delete -f mongo-svc.yaml -n bibi-devops-tools
                    kubectl delete -f mongo-secret.yaml -n bibi-devops-tools
                    kubectl delete -f bibi-ns.yaml
                  """
            }
        }
  }
}