pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  agent {
      kubernetes {
          label 'bibi-web-app'
          idleMinutes 5
          yamlFile 'microservices-in-two-pods-fleet-dynamic-jenkins-on-ebs/jenkins_eks.yaml'
          defaultContainer 'jnlp'
       }
   }
 stages {
    stage('Push') {
      steps {
          withCredentials([usernamePassword(credentialsId: 'aws_hub_ecr_repo', passwordVariable: 'pass', usernameVariable: 'user')]) {
              sh """
                 cat ~/.aws/config
                 aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 019273956931.dkr.ecr.eu-west-1.amazonaws.com
                 docker pull 019273956931.dkr.ecr.eu-west-1.amazonaws.com/bibi-ecr-repo:ubuntu_1.0.26
                 docker ps -a
                 curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
                 chmod 755 ./kubectl
                 sudo cp -rf ./kubectl /usr/local/bin/kubectl
                 kubectl get svc
                 cd microservices-in-two-pods-fleet-dynamic-ebs
                 kubectl apply -f bibi-ns.yaml
                 kubectl apply -f mongo-secret.yaml -n bibi-ns
                 kubectl apply -f mongo-svc.yaml -n bibi-ns
                 kubectl apply -f mongodb-deployment.yaml -n bibi-ns
                 kubectl apply -f bibi_web_server_ex1.yaml -n bibi-ns
                 sleep 60
              """
          }
      }//steps
    }//stage
  }//stages
post {
        always {
                  sh """
                    cd microservices-in-two-pods-fleet-dynamic-ebs
                    kubectl delete -f bibi_web_server_ex1.yaml -n bibi-ns
                    kubectl delete -f mongodb-deployment.yaml -n bibi-ns
                    kubectl delete -f mongo-svc.yaml -n bibi-ns
                    kubectl delete -f mongo-secret.yaml -n bibi-ns
                    kubectl delete -f bibi-ns.yaml
                  """
        }
  }
}