apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bibi-argocd-web-app.yaml
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/bibiefrat/ubuntu:~1.0
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: master
    #argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/force-update: "true"
    argocd-image-updater.argoproj.io/update-strategy: name
    notifications.argoproj.io/subscribe.on-sync-succeeded.email.gmail": ""
spec:
  project: default
  source:
    repoURL: https://github.com/bibiefart/ci_cd_microservices.git
    targetRevision: master
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true