apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: bibiefrat/ubuntu:~1.0
  name: bibi-argocd-web-app.yaml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bibiefart/ci_cd_microservices.git
    targetRevision: master
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default