pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  environment {
        //PREV_BUILD_NUMBER = $($BUILD_NUMBER -1)
        PREV_BUILD_ID = "${BUILD_ID}"
    }
  agent {
    kubernetes {
      label 'bibi-web-app'
      idleMinutes 5
      yamlFile 'jenkins_k8s.yaml'
      defaultContainer 'jnlp'
   }
  }
  stages {
    stage('Deploy') {
      steps {
        container('inbound-agent') {
          withKubeConfig([namespace: "demo-app"]) {
              sh """
                 kubectl get pods
                 argocd login    argocd-server.argocd:80   --insecure --username admin --password a3bAcd01
                 kubectl apply -f argocd/bibi-argocd-web-app.yaml
                 argocd app  sync argocd/bibi-argocd-web-app.yaml
                 sleep 1000
              """
          }//withKubeConfig
        }//container
      }//steps
    }//stage
  }//stages

}