apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

namePrefix: kustomize-

resources:
- bibi_web_server_ex1.yaml
commonAnnotations:
  sample-go/version: v3
  argocd-image-updater.argoproj.io/git-branch: master