pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  agent { label 'ec2-fleet' }
 stages {
    stage('Push') {
      steps {
          withCredentials([usernamePassword(credentialsId: 'aws_hub_ecr_repo', passwordVariable: 'pass', usernameVariable: 'user')]) {
              sh """
                 cat ~/.aws/config
                 echo $pass | docker login --username $user --password-stdin 019273956931.dkr.ecr.eu-west-1.amazonaws.com
                 docker pull 019273956931.dkr.ecr.eu-west-1.amazonaws.com/bibi-ecr-repo:ubuntu_1.0.26
                 docker ps -a
                 curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
                 chmod 755 ./kubectl
                 sudo cp ./kubectl /usr/local/bin/kubectl
                 kubectl get svc
              """
          }
      }//steps
    }//stage
  }//stages
}