apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
type: Opaque
data:
  mysql_conn_str: "cm9vdDpwYXNzd29yZEB0Y3AobXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDozMzA2KS9zdGF0c19kYg==" # cm9vdDpwYXNzd29yZEB0Y3AobXlzcWw6MzMwNikvc3RhdHNfZGI= # dXNlckB0Y3AobXlzcWw6MzMwNikvc3RhdHNfZGI= # base64 encoded value of mysql connectionString of format user:password@tcp(mysql.default.svc.cluster.local:3306)/stats_db
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-mysql-secret
  namespace: default
spec:
  secretTargetRef:
  - parameter: connectionString
    name: mysql-secrets
    key: mysql_conn_str
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-scaledobject
  namespace: default
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod: 5 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: php-apache
  triggers:
  - type: mysql
    metadata:
      #password: "password"
      #host: "mysql.default.svc.cluster.local"
      #port: "3306"
      #dbName: "stats_db"
      #username: root
      queryValue: "4.4"
      activationQueryValue: "5.4"
      query: "SELECT CEIL(COUNT(*) / 2) FROM task_instance WHERE state='running' OR state='queued'"
    authenticationRef:
      name: keda-trigger-auth-mysql-secret