pipeline {
  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '3'))
    disableConcurrentBuilds()
    timestamps()
    timeout(time: 10, unit: 'MINUTES')
  }
  agent {
    kubernetes {
      label 'bibi-web-app'
      idleMinutes 5
      yamlFile 'jenkins_k8s.yaml'
      defaultContainer 'jnlp'
   }
  }
  stages {
    stage('Build') {
      steps {
        container('maven') {
          sh """
            pwd
            """
        }
      }
    }
    stage('Test') {
      steps {
        container('maven') {
          sh """
             ls -ltr
          """
        }
      }
    }
    stage('Push') {
      steps {
        container('docker') {
          sh """
             docker ps -a
             aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 019273956931.dkr.ecr.eu-west-1.amazonaws.com
             docker tag ubuntu:latest 019273956931.dkr.ecr.eu-west-1.amazonaws.com/bibi-ecr-repo:ubuntu_1.0.${env.BUILD_ID}
             docker push 019273956931.dkr.ecr.eu-west-1.amazonaws.com/bibi-ecr-repo:ubuntu_1.0.${env.BUILD_ID}
          """
        }//container
      }//steps
    }//stage
    stage('Deploy') {
      steps {
        container('inbound-agent') {
          withKubeConfig([namespace: "demo-app"]) {
              sh """
                 kubectl get pods
                 kubectl create namespace demo-app
                 cd microservices-in-two-pods
                 kubectl apply -f mongodb-deployment.yaml -n demo-app
                 sleep 5
                 kubectl apply -f bibi_web_server_ex1.yaml -n demo-app
                 sleep 80
              """
          }//withKubeConfig
        }//container
      }//steps
    }//stage
  }//stages
  post {
        always {
          container('inbound-agent') {
              //withKubeConfig([namespace: "demo-app"]) {
                  sh """
                    cd microservices-in-two-pods
                    kubectl delete -f bibi_web_server_ex1.yaml -n demo-app
                    sleep 5
                    kubectl delete -f mongodb-deployment.yaml -n demo-app
                    kubectl delete namespace demo-app
                  """
              //}//withKubeConfig
          }//container

        }
  }
}