kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-standard-jenkins
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: bibi-devops-tools
spec:
  storageClassName: aws-standard-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
