apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bibi-web-server-deployment
  labels:
    dep: bibi-web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      volumes:
        - name: api-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secrets-provider"
      containers:
      - name: my-web-app
        image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/bibi-ecr-repo:my_web_app
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        - name: MONGO_URL_RUN
          value: "mongodb://10.100.1.143:20000"
        - name: MONGO
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        ports:
        - containerPort: 8088
        volumeMounts:
          - name: api-secret
            mountPath: "/mnt/secrets-store"
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: bibi-web-server-service
spec:
  type: NodePort
  #type: ClusterIP
  selector:
    app: web-app
  ports:
    - name: "http"
      port: 8088
      targetPort: 8088
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bibi-ingress-network
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: ubuntu # this can be omitted if there is a default ingress class:  kubectl get ingressclass ; kubectl describe ingressclass ubuntu
  rules:
    - host: bibi-web-server.info
      http:
        paths:
          - path: / # this is the path the ingress network will expose in order to get to internal service "<service-ip>:8088/"
            pathType: Prefix
            backend:
              service:
                name: bibi-web-server-service
                port:
                  number: 8088