apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::019273956931:role/eksctl-devops-int-2023-addon-iamserviceaccou-Role1-A5ZE6SL2RP17