apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws
  secretObjects:
  - secretName: mongo-creds
    type: Opaque
    data:
    - objectName: username
      key: username
    - objectName: password
      key: password
  parameters:
    objects: |
        - objectName: "mongo-creds"
          objectType: "secretsmanager"
          jmesPath:
            - path: "username"
              objectAlias: "username"            
            - path: "password"
              objectAlias: "password"
